spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
    username: root
    url: jdbc:mysql://localhost/dbprogettopawm?useSSL=false&allowMultiQueries=true&serverTimezone=UTC


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


